services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
      - "1882:1882"
    volumes:
      - ./node-red-data:/data
      - /dev/snd:/dev/snd
    environment:
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    links:
      - mqtt
      - influxdb
      - postgres
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tachos_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  telegraf:
    image: telegraf:1.16
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  backend:
    build: ./backend
    container_name: backend_tachos
    ports:
      - "3000:3000"
    links:
      - postgres
      - influxdb
  frontend:
    image: nginx:alpine
    container_name: frontend_tachos
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
volumes:
  influxdb-data:
  postgres-data:
